### ISSUE TITLE
Error loading main.qml file module “org.kde.plasma.timekeeper” is not installed

### ISSUE THREAD

**Issue by kupiqu** [grulja/plasma-timekeeper#1]
I wanted to give it a try and I built it with no errors but the applet complains:

Error loading QML file: file:///usr/share/plasma/plasmoids/org.kde.plasma.timekeeper/contents/ui/main.qml:24:1 module “org.kde.plasma.timekeeper” is not installed

I tried to make the version match to 0.2 in metadesktop files, but it didn’t work either.

Any hint?

**Comment by grulja** [comment]
You need to use -DQML_INSTALL_DIR:PATH="xxxxx" in cmake to specify the path where you have installed other qml libs. In my case it's "/usr/lib64/qt5/qml".

**Comment by kupiqu** [comment]
That was it, thanks!

Perhaps, it would be good to add the Install info to the README.md file

PS For the case you want to do it,  in (K)Ubuntu the folder is /usr/lib/x86_64-linux-gnu/qt5/qml
