### ISSUE TITLE
Needs a CompactRepresentation (aka make it work in panel)

### ISSUE THREAD

**Issue by mck182** [grulja/plasma-timekeeper#2]
When put it panel, it creates the full representation in there, which is really not suited for panel.

It needs a CompactRepresentation and be an icon when in panel _OR_ show an icon of the current app. Or something.

**Comment by grulja** [comment]
Weird, it has a CompactRepresentation.

**Comment by mck182** [comment]
Ah, you're absolutely correct. Must be hidpi sizing or something

![](http://paste.opensuse.org/view/raw/8ecb8b8a)

**Comment by grulja** [comment]
This happens when your panel is not high enough to display two lines of text. I'll have to do the same as  the digital clock applet does, to display the time and the date in one row.

**Comment by grulja** [comment]
I added horizontal layout for case that the panel is not high enough. It doesn't work correctly when you switch between layouts (e.g you change the panel height), but when you add it for the first time or restart plasmashell then it works as it should. No idea how to solve it.
