### ISSUE TITLE
the plasmoid messes up in panels of narrow width

### ISSUE THREAD

**Issue by kupiqu** [grulja/plasma-timekeeper#4]
It shows time on top of icon (time should not be visible, only icon), and even time takes exta space out of boundary, for instance if using timekeeper in systray, time appears out of the systray itself.

**Comment by npit** [comment]
Can confirm
https://s27.postimg.org/cvqczy4pv/Screenshot_20161230_193639.png

**Comment by kupiqu** [comment]
If some users don't care about labels, they can use https://github.com/kupiqu/plasma-timekeeper instead
